#!/bin/bash

# name   : mac-changerPro
# url    : https://github.com/4m3rr0r/mac-changerPro
# author : 4m3rr0r


banner() {
  echo -e "\033[31m_________\033[0m"
  echo -e "\033[32m|         |\033[0m"
  echo -e "\033[33m| MAC Changer Pro |\033[0m"
  echo -e "\033[34m|_________|\033[0m"
}

check_root() {
  if [[ $EUID -ne 0 ]]; then
    echo ""
    echo -e "\033[031m Please run as root\033[0m"
    exit 1
  fi
}

install_macchanger() {
  if ! command -v macchanger > /dev/null; then
    echo ""
    echo -e "\033[032m Please wait, installing Macchanger\033[0m"
    sudo apt-get update > /dev/null
    sudo apt-get install -y macchanger > /dev/null
    echo ""
    echo -e "\033[032m Successful Installation\033[0m"
    exit 1
  fi
}

install_macchangerPro() {
  if ! command -v mac-changerPro > /dev/null; then
    sudo cp mac-changerPro /usr/local/bin > /dev/null
    sudo mac-changerPro -h
    exit 1
  fi
}

change_mac_address() {
  local interface=$1
  macchanger -l > list.txt
  ouimac=$(shuf -n 1 list.txt | awk '{print $3}')
  uaamac=$(printf '%02x:%02x:%02x' $((RANDOM % 256)) $((RANDOM % 256)) $((RANDOM % 256)))
  sudo ifconfig "$interface" down
  macchanger -m "$ouimac:$uaamac" "$interface"
  sudo ifconfig "$interface" up
}

show_help() {
  echo ""
  echo "Usage: $0 -i <interface>"
  echo ""
  echo "Change the MAC address of the specified network interface."
  echo ""
  echo "Options:"
  echo "  -i, --interface    Specify the network interface (e.g., eth0, wlan0 etc)"
  echo "  -h, --help         Display this help menu"
  exit 1
}

banner
check_root
install_macchanger
install_macchangerPro

if [ $# -eq 0 ]; then
  show_help
fi

while [ "$#" -gt 0 ]; do
  case $1 in
    -i | --interface)
      shift
      if [ -z "$1" ]; then
        echo ""
        echo -e "\033[31mError: Missing argument for -i option\033[0m"
        show_help
      fi
      interface_name=$1
      echo ""
      echo -e "\033[35mChanging the MAC address of the $interface_name interface\033[0;32m"
      change_mac_address "$interface_name"
      ;;
    -h | --help)
      show_help
      ;;
    *)
      echo ""
      echo -e "\033[31mError: Invalid option\033[0m"
      show_help
      ;;
  esac
  shift
done
